plan_id: plan-7ea84730-f905-4c90-addb-0aee174e795e
tasks:
- task_id: task-1
  agent_id: financial-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
- task_id: task-2
  agent_id: risk-management-agent
  action: null
  dependencies:
  - financial-management-agent
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-03-01T08:39:35.530266Z'
version: 577
